MODULE xSectionModule

  USE ISO_C_BINDING

  TYPE, BIND(C) :: xSection2
    DOUBLE PRECISION :: SIG2
    DOUBLE PRECISION :: SIG2E
    DOUBLE PRECISION :: T2GGMA
    DOUBLE PRECISION :: T2GMAX(2500)
    DOUBLE PRECISION :: XX2(50,2)
    DOUBLE PRECISION :: FFGO2
    DOUBLE PRECISION :: DNCG2
    DOUBLE PRECISION :: FFLO2
    DOUBLE PRECISION :: DNCL2
    DOUBLE PRECISION :: GOLD2
    DOUBLE PRECISION :: NM2(2500)
    INTEGER :: NDO2
    DOUBLE PRECISION :: NTOT2
    DOUBLE PRECISION :: NCAL2
    DOUBLE PRECISION :: NCA12
    DOUBLE PRECISION :: NCA22
    DOUBLE PRECISION :: IBIM2
    DOUBLE PRECISION :: JCOR2
    LOGICAL :: LGLO2
    LOGICAL :: LLOC2
  END TYPE

  TYPE, BIND(C) :: xSection2C
    DOUBLE PRECISION :: SIG2C
    DOUBLE PRECISION :: SIG2EC
    DOUBLE PRECISION :: T2GMAC
    DOUBLE PRECISION :: T2MAXC(2500)
    DOUBLE PRECISION :: XX2C(50,2)
    DOUBLE PRECISION :: FFGO2C
    DOUBLE PRECISION :: DNCG2C
    DOUBLE PRECISION :: FFLO2C
    DOUBLE PRECISION :: DNCL2C
    DOUBLE PRECISION :: GOLD2C
    DOUBLE PRECISION :: NM2C(2500)
    INTEGER :: NDO2C
    DOUBLE PRECISION :: NTOT2C
    DOUBLE PRECISION :: NCAL2C
    DOUBLE PRECISION :: NCA12C
    DOUBLE PRECISION :: NCA22C
    DOUBLE PRECISION :: IBIM2C
    DOUBLE PRECISION :: JCOR2C
    LOGICAL :: LGLO2C
    LOGICAL :: LLOC2C
  END TYPE

  TYPE, BIND(C) :: xSection2E
    DOUBLE PRECISION :: SIG2L
    DOUBLE PRECISION :: SIG2EE
    DOUBLE PRECISION :: T2GMAE
    DOUBLE PRECISION :: T2MAXE(50)
    DOUBLE PRECISION :: XX2C(50,1)
    DOUBLE PRECISION :: FFGO2E
    DOUBLE PRECISION :: DNCG2E
    DOUBLE PRECISION :: FFLO2E
    DOUBLE PRECISION :: DNCL2E
    DOUBLE PRECISION :: GOLD2E
    DOUBLE PRECISION :: NM2E(50)
    INTEGER :: NDO2E
    DOUBLE PRECISION :: NTOT2E
    DOUBLE PRECISION :: NCAL2E
    DOUBLE PRECISION :: NCA12E
    DOUBLE PRECISION :: NCA22E
    DOUBLE PRECISION :: IBIM2E
    DOUBLE PRECISION :: JCOR2E
    LOGICAL :: LGLO2E
    LOGICAL :: LLOC2E
  END TYPE

  TYPE, BIND(C) :: xSection31
    DOUBLE PRECISION :: SIG31
    DOUBLE PRECISION :: SIG31E
    DOUBLE PRECISION :: T31GMA
    DOUBLE PRECISION :: T31MAX(7776)
    DOUBLE PRECISION :: XX31(50,5)
    DOUBLE PRECISION :: FFGO31
    DOUBLE PRECISION :: DNCG31
    DOUBLE PRECISION :: FFLO31
    DOUBLE PRECISION :: DNCL31
    DOUBLE PRECISION :: GOLD31
    DOUBLE PRECISION :: SI31
    DOUBLE PRECISION :: SI2N31
    DOUBLE PRECISION :: SWGT31
    DOUBLE PRECISION :: SCHI31
    DOUBLE PRECISION :: IT31
    DOUBLE PRECISION :: NM31(7776)
    INTEGER :: NDO31
    DOUBLE PRECISION :: NTOT31
    DOUBLE PRECISION :: NCAL31
    DOUBLE PRECISION :: NCA131
    DOUBLE PRECISION :: NCA231
    DOUBLE PRECISION :: IBIM31
    DOUBLE PRECISION :: JCOR31
    LOGICAL :: LGLO31
    LOGICAL :: LLOC31
  END TYPE

  TYPE, BIND(C) :: xSection32
    DOUBLE PRECISION :: SIG32
    DOUBLE PRECISION :: SIG32E
    DOUBLE PRECISION :: T32GMA
    DOUBLE PRECISION :: T32MAX(7776)
    DOUBLE PRECISION :: XX32(50,5)
    DOUBLE PRECISION :: FFGO32
    DOUBLE PRECISION :: DNCG32
    DOUBLE PRECISION :: FFLO32
    DOUBLE PRECISION :: DNCL32
    DOUBLE PRECISION :: GOLD32
    DOUBLE PRECISION :: SI32
    DOUBLE PRECISION :: SI2N32
    DOUBLE PRECISION :: SWGT32
    DOUBLE PRECISION :: SCHI32
    DOUBLE PRECISION :: IT32
    DOUBLE PRECISION :: NM32(7776)
    INTEGER :: NDO32
    DOUBLE PRECISION :: NTOT32
    DOUBLE PRECISION :: NCAL32
    DOUBLE PRECISION :: NCA132
    DOUBLE PRECISION :: NCA232
    DOUBLE PRECISION :: IBIM32
    DOUBLE PRECISION :: JCOR32
    LOGICAL :: LGLO32
    LOGICAL :: LLOC32
  END TYPE

  TYPE, BIND(C) :: xSection33
    DOUBLE PRECISION :: SIG33
    DOUBLE PRECISION :: SIG33E
    DOUBLE PRECISION :: T33GMA
    DOUBLE PRECISION :: T33MAX(7776)
    DOUBLE PRECISION :: XX33(50,5)
    DOUBLE PRECISION :: FFGO33
    DOUBLE PRECISION :: DNCG33
    DOUBLE PRECISION :: FFLO33
    DOUBLE PRECISION :: DNCL33
    DOUBLE PRECISION :: GOLD33
    DOUBLE PRECISION :: SI33
    DOUBLE PRECISION :: SI2N33
    DOUBLE PRECISION :: SWGT33
    DOUBLE PRECISION :: SCHI33
    DOUBLE PRECISION :: IT33
    DOUBLE PRECISION :: NM33(7776)
    INTEGER :: NDO33
    DOUBLE PRECISION :: NTOT33
    DOUBLE PRECISION :: NCAL33
    DOUBLE PRECISION :: NCA133
    DOUBLE PRECISION :: NCA233
    DOUBLE PRECISION :: IBIM33
    DOUBLE PRECISION :: JCOR33
    LOGICAL :: LGLO33
    LOGICAL :: LLOC33
  END TYPE

  TYPE, BIND(C) :: xSection34
    DOUBLE PRECISION :: SIG34
    DOUBLE PRECISION :: SIG34E
    DOUBLE PRECISION :: T34GMA
    DOUBLE PRECISION :: T34MAX(7776)
    DOUBLE PRECISION :: XX34(50,5)
    DOUBLE PRECISION :: FFGO34
    DOUBLE PRECISION :: DNCG34
    DOUBLE PRECISION :: FFLO34
    DOUBLE PRECISION :: DNCL34
    DOUBLE PRECISION :: GOLD34
    DOUBLE PRECISION :: SI34
    DOUBLE PRECISION :: SI2N34
    DOUBLE PRECISION :: SWGT34
    DOUBLE PRECISION :: SCHI34
    DOUBLE PRECISION :: IT34
    DOUBLE PRECISION :: NM34(7776)
    INTEGER :: NDO34
    DOUBLE PRECISION :: NTOT34
    DOUBLE PRECISION :: NCAL34
    DOUBLE PRECISION :: NCA134
    DOUBLE PRECISION :: NCA234
    DOUBLE PRECISION :: IBIM34
    DOUBLE PRECISION :: JCOR34
    LOGICAL :: LGLO34
    LOGICAL :: LLOC34
  END TYPE

  TYPE, BIND(C) :: xSection31C
    DOUBLE PRECISION :: SIG31C
    DOUBLE PRECISION :: SG31EC
    DOUBLE PRECISION :: T31GMC
    DOUBLE PRECISION :: T31MXC(7776)
    DOUBLE PRECISION :: XX31C(50,5)
    DOUBLE PRECISION :: FFG31C
    DOUBLE PRECISION :: DNG31C
    DOUBLE PRECISION :: FFL31C
    DOUBLE PRECISION :: DNL31C
    DOUBLE PRECISION :: GLD31C
    DOUBLE PRECISION :: SI31C
    DOUBLE PRECISION :: S2N31C
    DOUBLE PRECISION :: SWT31C
    DOUBLE PRECISION :: SCH31C
    DOUBLE PRECISION :: IT31C
    DOUBLE PRECISION :: NM31C(7776)
    INTEGER :: NDO31C
    DOUBLE PRECISION :: NTT31C
    DOUBLE PRECISION :: NCL31C
    DOUBLE PRECISION :: NC131C
    DOUBLE PRECISION :: NC231C
    DOUBLE PRECISION :: IBM31C
    DOUBLE PRECISION :: JCR31C
    LOGICAL :: LGL31C
    LOGICAL :: LLC31C
  END TYPE

  TYPE, BIND(C) :: xSection32C
    DOUBLE PRECISION :: SIG32C
    DOUBLE PRECISION :: SG32EC
    DOUBLE PRECISION :: T32GMC
    DOUBLE PRECISION :: T32MXC(7776)
    DOUBLE PRECISION :: XX32C(50,5)
    DOUBLE PRECISION :: FFG32C
    DOUBLE PRECISION :: DNG32C
    DOUBLE PRECISION :: FFL32C
    DOUBLE PRECISION :: DNL32C
    DOUBLE PRECISION :: GLD32C
    DOUBLE PRECISION :: SI32C
    DOUBLE PRECISION :: S2N32C
    DOUBLE PRECISION :: SWT32C
    DOUBLE PRECISION :: SCH32C
    DOUBLE PRECISION :: IT32C
    DOUBLE PRECISION :: NM32C(7776)
    INTEGER :: NDO32C
    DOUBLE PRECISION :: NTT32C
    DOUBLE PRECISION :: NCL32C
    DOUBLE PRECISION :: NC132C
    DOUBLE PRECISION :: NC232C
    DOUBLE PRECISION :: IBM32C
    DOUBLE PRECISION :: JCR32C
    LOGICAL :: LGL32C
    LOGICAL :: LLC32C
  END TYPE

  TYPE, BIND(C) :: xSection33C
    DOUBLE PRECISION :: SIG33C
    DOUBLE PRECISION :: SG33EC
    DOUBLE PRECISION :: T33GMC
    DOUBLE PRECISION :: T33MXC(7776)
    DOUBLE PRECISION :: XX33C(50,5)
    DOUBLE PRECISION :: FFG33C
    DOUBLE PRECISION :: DNG33C
    DOUBLE PRECISION :: FFL33C
    DOUBLE PRECISION :: DNL33C
    DOUBLE PRECISION :: GLD33C
    DOUBLE PRECISION :: SI33C
    DOUBLE PRECISION :: S2N33C
    DOUBLE PRECISION :: SWT33C
    DOUBLE PRECISION :: SCH33C
    DOUBLE PRECISION :: IT33C
    DOUBLE PRECISION :: NM33C(7776)
    INTEGER :: NDO33C
    DOUBLE PRECISION :: NTT33C
    DOUBLE PRECISION :: NCL33C
    DOUBLE PRECISION :: NC133C
    DOUBLE PRECISION :: NC233C
    DOUBLE PRECISION :: IBM33C
    DOUBLE PRECISION :: JCR33C
    LOGICAL :: LGL33C
    LOGICAL :: LLC33C
  END TYPE

  TYPE, BIND(C) :: xSection31E
    DOUBLE PRECISION :: SIG31L
    DOUBLE PRECISION :: SG31EE
    DOUBLE PRECISION :: T31GME
    DOUBLE PRECISION :: T31MXE(4096)
    DOUBLE PRECISION :: XX31E(50,4)
    DOUBLE PRECISION :: FFG31E
    DOUBLE PRECISION :: DNG31E
    DOUBLE PRECISION :: FFL31E
    DOUBLE PRECISION :: DNL31E
    DOUBLE PRECISION :: GLD31E
    DOUBLE PRECISION :: SI31E
    DOUBLE PRECISION :: S2N31E
    DOUBLE PRECISION :: SWT31E
    DOUBLE PRECISION :: SCH31E
    DOUBLE PRECISION :: IT31E
    DOUBLE PRECISION :: NM31E(4096)
    INTEGER :: NDO31E
    DOUBLE PRECISION :: NTT31E
    DOUBLE PRECISION :: NCL31E
    DOUBLE PRECISION :: NC131E
    DOUBLE PRECISION :: NC231E
    DOUBLE PRECISION :: IBM31E
    DOUBLE PRECISION :: JCR31E
    LOGICAL :: LGL31E
    LOGICAL :: LLC31E
  END TYPE

  TYPE, BIND(C) :: xSection32E
    DOUBLE PRECISION :: SIG32L
    DOUBLE PRECISION :: SG32EE
    DOUBLE PRECISION :: T32GME
    DOUBLE PRECISION :: T32MXE(4096)
    DOUBLE PRECISION :: XX32E(50,4)
    DOUBLE PRECISION :: FFG32E
    DOUBLE PRECISION :: DNG32E
    DOUBLE PRECISION :: FFL32E
    DOUBLE PRECISION :: DNL32E
    DOUBLE PRECISION :: GLD32E
    DOUBLE PRECISION :: SI32E
    DOUBLE PRECISION :: S2N32E
    DOUBLE PRECISION :: SWT32E
    DOUBLE PRECISION :: SCH32E
    DOUBLE PRECISION :: IT32E
    DOUBLE PRECISION :: NM32E(4096)
    INTEGER :: NDO32E
    DOUBLE PRECISION :: NTT32E
    DOUBLE PRECISION :: NCL32E
    DOUBLE PRECISION :: NC132E
    DOUBLE PRECISION :: NC232E
    DOUBLE PRECISION :: IBM32E
    DOUBLE PRECISION :: JCR32E
    LOGICAL :: LGL32E
    LOGICAL :: LLC32E
  END TYPE

  TYPE, BIND(C) :: xSection33E
    DOUBLE PRECISION :: SIG33L
    DOUBLE PRECISION :: SG33EE
    DOUBLE PRECISION :: T33GME
    DOUBLE PRECISION :: T33MXE(4096)
    DOUBLE PRECISION :: XX33E(50,4)
    DOUBLE PRECISION :: FFG33E
    DOUBLE PRECISION :: DNG33E
    DOUBLE PRECISION :: FFL33E
    DOUBLE PRECISION :: DNL33E
    DOUBLE PRECISION :: GLD33E
    DOUBLE PRECISION :: SI33E
    DOUBLE PRECISION :: S2N33E
    DOUBLE PRECISION :: SWT33E
    DOUBLE PRECISION :: SCH33E
    DOUBLE PRECISION :: IT33E
    DOUBLE PRECISION :: NM33E(4096)
    INTEGER :: NDO33E
    DOUBLE PRECISION :: NTT33E
    DOUBLE PRECISION :: NCL33E
    DOUBLE PRECISION :: NC133E
    DOUBLE PRECISION :: NC233E
    DOUBLE PRECISION :: IBM33E
    DOUBLE PRECISION :: JCR33E
    LOGICAL :: LGL33E
    LOGICAL :: LLC33E
  END TYPE

END MODULE
